### ISSUE TITLE
About tqdm and its constantly decreasing iterative speed

### ISSUE THREAD

**Issue by fredchenjialin** [carpedm20/deep-rl-tensorflow#31]
hello, I'm very confused about the speed of iteration.
Within a few minutes after the program runs, the value of it/s was pretty big and it runs very fast that's what I'd love to see. But, in the process of running, the value of it/s is constantly decreasing. After about 30 minutes, the value will drop from about 10000 to 900, and it's going down.

Is this the problem of setting up the GPU or tqdm?

The graphics card I used is two Nvidia K40.

![image](https://user-images.githubusercontent.com/5558295/32639050-e589d5fa-c5fc-11e7-87f0-21531846962a.png)
The picture below shows 30 minutes later
![image](https://user-images.githubusercontent.com/5558295/32639057-f1b26982-c5fc-11e7-9d0e-8d98834e0dbf.png)

for nvidia-smi
![image](https://user-images.githubusercontent.com/5558295/32639111-3a577e98-c5fd-11e7-9396-efff6b140185.png)

**Comment by carpedm20** [comment]
Did you tried training without `tqdm`? I know tqdm sometimes cause problem in multi-threading setting but this code does not use such fancy techniques.. so I assume it's not a problem of `tqdm`.

**Comment by ppwwyyxx** [comment]
In a typical DQN, at the beginning the training runs with random exploration, but later it will gradually start to use the network for exploration. So some sort of slow-down is normal. (although 10x is definitely too much)

**Comment by carpedm20** [comment]
@ppwwyyxx I thought about it but the step in both images is quite large. I also found that the log `avg_r: 0.001234 ...` is only printed when the random exploration is finished which means they are both in the training phase.

**Comment by ppwwyyxx** [comment]
In training phase you're decreasing `epsilon` I guess? This also gradually slows things down.

**Comment by carpedm20** [comment]
Oh.. yes. That's right. [That](https://github.com/carpedm20/deep-rl-tensorflow/blob/master/agents/agent.py#L145-L150) explains the slow down.

**Comment by fredchenjialin** [comment]
Thank you。@carpedm20 @ppwwyyxx 
About "you can fit multiple (more than 10) experiments in a single K40", how to do this? or How can I use my GPU more efficiently? Can I increase the batch_size or memory_size in main.py?

`flags.DEFINE_integer('batch_size', 32, 'The size of batch for minibatch training')`
`flags.DEFINE_integer('memory_size', 100, 'The size of experience memory (*= scale)')`

**Comment by carpedm20** [comment]
What you need to do is just pull the code and run it. See changs in a6a836edd8cc9cba41e84eaa54dce20c3b24a5b2 fo detials

**Comment by fredchenjialin** [comment]
ok, thank you. @carpedm20

**Comment by ppwwyyxx** [comment]
Isn't this still considered a bug?
Even if it's always using the network to predict, the extra work is just one forward time every step.
The training happens every 4 steps, so it's 32 forward/backward every 4 steps.
The prediction shouldn't make training 10x slower..
